// DO NOT EDIT THIS FILE. THIS FILE IS USED BY DESIGN SYSTEMS.
import 'package:flutter/material.dart';
import 'package:iconsax/iconsax.dart';

class MinyIcons {
  static const IconData outline_arrow_up = Iconsax.arrow_up_2;
  static const IconData plus = Icons.add_rounded;
  static const IconData fill_scan = Iconsax.scan5;
  static const IconData outline_send_money = Iconsax.card_send;
  static const IconData outline_receive_money = Iconsax.card_receive;
  static const IconData cross = Icons.close_rounded;
  static const IconData filter = Iconsax.setting_4;
}
