const appName = 'Tackle Pay';
const incomeText = 'Income';
const expenseText = 'Expense';
const checkZero = '0';
const checkMinus = '-';
const newExpense = 'New Expense';
const payUsingText = 'Pay Using';
const vsLastMonthText = '  vs. last month';
const balanceAmountText = 'Balance Amount';
