const appName = 'Tackle Pay';
const incomeText = 'Income';
const expenseText = 'Expense';
const checkZero = '0';
const checkMinus = '-';
const vsLastMonthText = '  vs. last month';
const balanceAmountText = 'Balance Amount';
const noDateSelected = 'No date Selected';
const payDate = 'Pay Date';
