# .github/workflows/flutter_ci.yml
name: Flutter CI

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter-version: [3.24.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Dart Format
        run: dart format . --set-exit-if-changed

      - name: Dart Analyze
        run: flutter analyze --fatal-infos .
